In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from IPython.display import display

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 1000)
pd.set_option("display.max_colwidth", None)
plt.rcParams.update({'figure.figsize': (12, 6),'figure.dpi':120})

In [2]:
orders = pd.read_csv(
    "../data/cleaned/cleaned_orders.csv",
    parse_dates=["created_at"]
)

order_items = pd.read_csv(
    "../data/cleaned/cleaned_order_items.csv",
    parse_dates=["created_at"]
)

order_item_refunds = pd.read_csv(
    "../data/cleaned/cleaned_order_item_refunds.csv",
    parse_dates=["created_at"]
)

products = pd.read_csv(
    "../data/cleaned/cleaned_products.csv",
    parse_dates=["created_at"]
)

website_sessions = pd.read_csv(
    "../data/cleaned/cleaned_website_sessions.csv",
    parse_dates=["created_at"]
)

website_pageviews = pd.read_csv(
    "../data/cleaned/cleaned_website_pageviews.csv",
    parse_dates=["created_at"]
)

In [5]:
order_details_dataset = pd.merge(orders, order_items, on = "order_id",suffixes=('_orders', '_orderitems'))

In [6]:
order_details_dataset.sample(10)

       order_id   created_at_orders  website_session_id  user_id  primary_product_id  items_purchased  price_usd_orders  cogs_usd_orders  year_orders  month_orders  day_orders  hour_orders day_name_orders  order_item_id created_at_orderitems  product_id  is_primary_item  price_usd_orderitems  cogs_usd_orderitems  year_orderitems  month_orderitems  day_orderitems  hour_orderitems day_name_orderitems
14911     13731 2014-04-17 09:53:36              231485   199252                   1                1             49.99            19.49         2014             4          17            9        Thursday          14912   2014-04-17 09:53:36           1                1                 49.99                19.49             2014                 4              17                9            Thursday
33062     27106 2015-01-04 20:54:27              411358   308546                   3                1             45.99            14.49         2015             1           4           20          Sunday          33063   2015-01-04 20:54:27           3                1                 45.99                14.49             2015                 1               4               20              Sunday
443         444 2012-07-09 13:49:41               14354    13346                   1                1             49.99            19.49         2012             7           9           13          Monday            444   2012-07-09 13:49:41           1                1                 49.99                19.49             2012                 7               9               13              Monday
32942     27015 2015-01-02 17:24:12              410306   345551                   1                2             79.98            28.98         2015             1           2           17          Friday          32943   2015-01-02 17:24:12           1                1                 49.99                19.49             2015                 1               2               17              Friday
3358       3359 2013-02-21 19:42:48               74628    66307                   1                1             49.99            19.49         2013             2          21           19        Thursday           3359   2013-02-21 19:42:48           1                1                 49.99                19.49             2013                 2              21               19            Thursday
34406     28101 2015-01-19 14:49:54              423497   355693                   1                2            109.98            41.98         2015             1          19           14          Monday          34407   2015-01-19 14:49:54           2                0                 59.99                22.49             2015                 1              19               14              Monday
13352     12561 2014-03-15 21:27:23              214433   185479                   1                2             79.98            28.98         2014             3          15           21        Saturday          13353   2014-03-15 21:27:23           4                0                 29.99                 9.49             2014                 3              15               21            Saturday
32017     26321 2014-12-23 17:52:37              401551   307597                   1                2            109.98            41.98         2014            12          23           17         Tuesday          32018   2014-12-23 17:52:37           1                1                 49.99                19.49             2014                12              23               17             Tuesday
34890     28456 2015-01-24 02:45:37              427774   358932                   4                1             29.99             9.49         2015             1          24            2        Saturday          34891   2015-01-24 02:45:37           4                1                 29.99                 9.49             2015                 1              24                2            Saturday
12158     11669 2014-02-19 00:09:58              200455   173829                   1                2             79.98            28.98         2014             2          19            0       Wednesday          12159   2014-02-19 00:09:58           1                1                 49.99                19.49             2014                 2              19                0           Wednesday

In [7]:
cross_sale_dataset = order_details_dataset.groupby(['primary_product_id', 'product_id'])['order_item_id'].count().reset_index()

In [8]:
cross_sale_dataset

    primary_product_id  product_id  order_item_id
0                    1           1          23861
1                    1           2            872
2                    1           3           1759
3                    1           4           3126
4                    2           1             72
5                    2           2           4803
6                    2           3            136
7                    2           4            671
8                    3           1            277
9                    3           2            112
10                   3           3           3068
11                   3           4            640
12                   4           1             16
13                   4           2              9
14                   4           3             22
15                   4           4            581